# permissions for end users to edit vnfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vnf-editor-role
rules:
- apiGroups:
  - nfv.dcn.com
  resources:
  - vnfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nfv.dcn.com
  resources:
  - vnfs/status
  verbs:
  - get
